# Generated by Django 5.1.1 on 2024-10-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='discription',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
